version: "3.8"

services:
  api:
    image: vimeo-upload-watch-api:latest
    build:
      context: ../
      dockerfile: packages/api/Dockerfile
    container_name: api
    ports:
      - 5000:5000
  web:
    image: vimeo-upload-watch-web:latest
    container_name: web
    ports:
      - 3000:3000
    depends_on:
      - api
    stdin_open: true
