version: "3.8"

services:
  app:
    image: vimeo-upload-watch:latest
    build:
      context: ../
      dockerfile: Dockerfile
  api:
    image: vimeo-upload-watch:latest
    container_name: api
    ports:
      - 5000:5000
  web:
    image: vimeo-upload-watch:latest
    container_name: web
    ports:
      - 3000:3000
    depends_on:
      - api
